### ISSUE TITLE
Contribute Section

### ISSUE THREAD

**Issue by simplymathematics** [thenextbilliononline/thenextbillion.online#27]
- [x] Change the nav, and default files from contact to contribute
- [x] Invite people to contribute
- [x] Move/copy meta page to {site.url}/meta, currently lives as the front page of the wiki
- [x] Point them to the meta page (#35) that discusses our philosophy, rules and guidelines.
~~~Set up mail server~~~ #22

**Comment by meyerscr** [comment]
Maybe change to contribute?
