### ISSUE TITLE
Meta Layout

### ISSUE THREAD

**Issue by simplymathematics** [thenextbilliononline/thenextbillion.online#35]
- [x] Make a meta page for use with site rules, philsosophy, staff page, etc.
- [x] Make Meta layout for jekyll
- [x] Automate additions to sidebar, following the folder layout /meta in the root directory.
- [x] Site Rules/guidelines
- [x] Add spacing between the header image and the first h1
- [x] Play with font sizes 
- [x] Play with spaces between paragraphs.
- [x] Nav bar is unreadable when you scroll down.

**Comment by simplymathematics** [comment]
Prose.io: http://prose.io/#thenextbilliononline/thenextbillion.online/blob/master

**Comment by simplymathematics** [comment]
BUG: 
@tati
The Meta Layout needs to make the text larger for the bullets under <h3>

**Comment by tati** [comment]
fixed all but the side bar with https://github.com/thenextbilliononline/thenextbillion.online/pull/56
