### ISSUE TITLE
Contact Bar

### ISSUE THREAD

**Issue by simplymathematics** [thenextbilliononline/thenextbillion.online#46]
- [x] Make a contact section to go under the contribute section on the main page.
- [x] Incorporate licensing stuff
- [x] Social Media links
- [x] email
Please do this all using the _config.yml settings instead of hard-coding the html. This will allow us to change/add social media links more easily. <3

**Comment by simplymathematics** [comment]
licensing copy:
All original content is licensed under GPLv3. All other content is licensed under their respective [licenses](thenextbillion.online/license) and is appropriately noted at the bottom of the content.

**Comment by brazilian-code** [comment]
Made the new contact section bellow the contribute, there are no other social media to add (at least none were created yet).
