### ISSUE TITLE
Style-Guide

### ISSUE THREAD

**Issue by simplymathematics** [thenextbilliononline/thenextbillion.online#47]
- [x] Create new site palette 
- [x] document it
- [ ] Include subset of icons from font-awesome repo
- [x] Document Html layouts and CSS
- [x] place at thenextbillion.online/style-guide
- [x] font guide

**Comment by brazilian-code** [comment]
[ ] font guide

**Comment by simplymathematics** [comment]
#53 contains the available information
