### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by simplymathematics** [thenextbilliononline/thenextbillion.online#51]
- [x] Create footer with site map
- [x] Include prominent reference to the fact that the content is licensed under GPLv3
- [x] Revise copy as below
- [x] get rid of gap between first and second set for mobile
Site map:
About, Contact, Contribute, 
Wiki, Blog, [Software](https://github.com/thenextbillion.online)

**Comment by simplymathematics** [comment]
Copy for license section: 
```All original content available under [GPLv3](/license/GPLv3). All other content available under [their respective licenses](/license).```

**Comment by tati** [comment]
@meyerscr what do you think? Test it out live too...not sure 1) design is ok 2) that I got all links right

![screen shot 2017-05-06 at 9 38 03 pm](https://cloud.githubusercontent.com/assets/12241872/25777210/6d65a4d2-32a4-11e7-8444-2602a96dba02.png)

**Comment by simplymathematics** [comment]
Since the licenses stuff is directly below, you can just delete that link in the Site Map. It's not like anyone will ever read it. It's really just there for compliance. 

However the 3rd Row, 2nd column entry should be  
```[Software](https://github.com/thenextbilliononline)```

Additionally, we can drop the Guidelines link since it is in the contribute section. Only contributors should have easy access to the Meta portal anyway. At least for now. Eventually, we'll have full about page with corporate info and staff pics, I imagine. However, since this project isn't about _us_, but is about the code/content, it doesn't need to be accessible from the main page. 

I've updated the initial issue to reflect these changes. Sorry for making you double the work. :/

**Comment by tati** [comment]
@meyerscr uh I think I updated it correctly...saw your changes and believe I incorporated...let me know if not it's live rn

**Comment by simplymathematics** [comment]
@tati Yay!
