### ISSUE TITLE
Site Repo Folders

### ISSUE THREAD

**Issue by simplymathematics** [thenextbilliononline/thenextbillion.online#52]
- [ ] Make it so that only the 3 portals (wiki, blog, meta) are in the root folder, as well as the index file.
- [ ] Make all other sub portals exist in discrete folders so that the URLs are apparent (like current posts setup)
- [ ] license folder in the root directory since it applies to the whole site, not just the meta portal

The point of this is to make the site human readable, and allow people to contribute on Windows by writing files in Markdown (or using a generator) and dragging and dropping them into the appropriate folder using the github application. From there, they can commit no problem and enter the dev workflow without being a dev. 

This will be particularly useful for content creators of the blog/wiki. I can see professors writing up lessons in math/engineering/physics, but not having the patience to deal with github. If we can make it so that they drag and drop a file, that becomes totally doable. The sames goes for translators.
