### ISSUE TITLE
Blog and meta page styling

### ISSUE THREAD

**Issue by Christianhendricks** [thenextbilliononline/thenextbillion.online#53]
Please give feedback. 
![dscf3550 resized](https://cloud.githubusercontent.com/assets/21126726/25718090/d712b8a8-30d2-11e7-9dbf-06d5026cd5ec.gif)

![screen shot 2017-05-04 at 1 13 58 pm](https://cloud.githubusercontent.com/assets/21126726/25718200/2e389508-30d3-11e7-8a04-4057dffe7cc0.jpg)

![blog](https://cloud.githubusercontent.com/assets/21126726/25717922/20302648-30d2-11e7-9660-eb7a52dc42e3.jpg)

![wiki](https://cloud.githubusercontent.com/assets/21126726/25717921/202b8f7a-30d2-11e7-9921-9758fef5f9f0.jpg)

![blogv](https://cloud.githubusercontent.com/assets/21126726/25717925/2500e310-30d2-11e7-8155-1ae67ff03b23.jpg)

**Comment by simplymathematics** [comment]
All excellent. However, if the Blog is going to have the floating box like we saw before, then we should change background image to something that has some action around the borders, like DSCF3544 in the /img/b-roll folder. If the background is static, then we can just put a unique image at the top for each the wiki and blog. Additionally, there needs to be a space for an image within the blog as every blog should include one for easy excerpting and pushing to social media
I don't know if the best way to do this is within the layout or the markdown content. @tati What do you think?

**Comment by simplymathematics** [comment]
The Meta portal will also require a sidebar. For maximum code reuse, you can make a single sidebar template for _includes, and I can edit it from there for each portal. Due to technical reasons, the stylized wiki will host static content, and the edits will direct you to github.com/thenextbilliononline/thenextbillion.online/wiki. 

The wiki sidebar will function more like the one in that link, providing links to categories/pages, instead of user options. The site itself will not accept any user input.

**Comment by simplymathematics** [comment]
Please make sure all fonts are open source and that the license is in the licenses folder.

**Comment by simplymathematics** [comment]
@christianhendricks make sure to download a new copy of the repository before you touch any code. Most of the html has been handled. It's all documented in the respective issues.

**Comment by tati** [comment]
looks totally dope! Thank you !Tiny feedback is that the white on beige is a bit hard to read on the blog/meta h1's (or h2's not sure what those would be/are)...maybe just using black there for font makes sense?

Esp love the homepage header!

**Comment by tati** [comment]
@meyerscr I'd have to play around with Jekyll a little more before I can know how images would work in a blog post etc. Are you thinking something like having a header image?

**Comment by simplymathematics** [comment]
@tati Yeah a header image on the left side with text wrap, so it looks decent in the blog snapshots as well as the individual post page. This is also in issue #45

**Comment by meyerscr** [comment]
@Christianhendricks 
- [ ] Download a new copy of the [site code](github.com/thenextbilliononline/thenextbillion.online)
- [ ] Send me new header image
- [ ] Send me the color pallete. Due to the timeframe, and the garbage code of our template, I'll have to manually search and replace it. It also doesn't help that you can't run the site locally yet. It looks like that background image in the design stuff is a crop from the sandstorm pics. It will have to be a solid color.
- [ ] I need the icon and your guidance on where to put it (nav, header, etc). Look at the source code for details.
- [ ] If you want to make the CSS readable without breaking anything, feel free, but it's not strictly necessary.
- [ ] The learn more section will be very difficult to make into a link tomorrow, unless you can do it by yourself. I don't know enough html to make it work.
