### ISSUE TITLE
Lower Barrier of Entry for Content

### ISSUE THREAD

**Issue by simplymathematics** [thenextbilliononline/thenextbillion.online#58]
- [ ] Document markdown editor for Linux (Remarkable)
     - [ ] include plug-ins for table of contents
     - [ ] plug in for spell check
- [ ] Windows
- [ ] Mac (Macdown?)
