### ISSUE TITLE
Meta Assets

### ISSUE THREAD

**Issue by simplymathematics** [thenextbilliononline/thenextbillion.online#84]
- [ ] Sidebar
- [ ] Navigation (search or equivalent)
- [ ] Topic tags (planned and documented)
- [ ] New Header for the non-front page that is less obtrusive (maybe just the top bar and an icon)
